parameters:
#    vns_todo.example.class: Vns\TodoBundle\Example

services:
#    vns_todo.example:
#        class: %vns_todo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
